### ISSUE TITLE
Connection timeout on send

### ISSUE THREAD

**Issue by afpatmin** [mailjet/mailjet-apiv3-nodejs#247] opened 2023-06-22 15:49 UTC
We recently started getting timeout errors, this happened without us making any changes. 

Error: Unsuccessful: Status Code: "null" Message: "read ECONNRESET" at /workspace/node_modules/node-mailjet/mailjet-client.js:326:23

This seems related to #176 
We are using firebase functions

**Comment by fbuland** [comment] 2023-07-05 15:42
Same issue **randomly** since June 7th. No changes on our side.

Error: Unsuccessful: Error Code: "ECONNRESET" Message: "read ECONNRESET”
One time : Error: Unsuccessful: Error Code: "ECONNRESET" Message: "Client network socket disconnected before secure TLS connection was established"

Using Node.js on AppEngine of Google Cloud Platform.
upgrade to v6.0.2 of node-mailjet, but still the issue.

**Comment by ai-wintermute** [comment] 2023-07-14 14:01
Hi @fbuland, there were no library updates for the past couple of months so this issue doesn't seem to be related to the library itself. Can you please contact the Mailjet API developer [support team](https://www.mailjet.com/contact/support/) to address it?

**Comment by fbuland** [comment] 2023-07-15 10:32
Indeed, the issue is NOT from the library. 

Maijet Support explanations : 
> Having in mind that you are using GCP, the issue most probably boils down to a blocked IP. The only reason why we would be blocking an IP address attempting to connect to our servers would be that too many unauthenticated requests were made from said IP via SMTP or HTTP. With a platform such as GCP, it is not unlikely that you have started being assigned IPs that had previously been used by other users on that platform, the actions of whom resulted in such unauthenticated calls.

> Unfortunately, I can only check if a given IP is being blocked or not if I know its exact value (I cannot run this kind of check based on IP-ranges and on top of that, GCP utilizes hundreds of thousands of IPs, so checking each one is not a manageable task). I would recommend obtaining a TCP/IP capture in PCAP, that is recorded on the network level responsible for the request made to our server (as that way it would contain the public IP from which the call is being made)

**Comment by ai-wintermute** [comment] 2023-07-17 12:40
@fbuland thank you for confirming this! I'm closing the ticket in this case.

**Closed by ai-wintermute** 2023-07-17 12:40 UTC
